title: Shuao Chen
description: Information Theory Notes

url: "https://shuao-chen.github.io"
baseurl: ""

theme: minima
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:title/

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
